import "~/styles/globals.css";
import Image from 'next/image'
import { Inter } from "next/font/google";
import { ComboboxDropdownMenu } from "~/components/ui/menu";
import Link from "next/link";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Monkey Factory",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="">
      {/* <div className="p-4"> <Link href="/">Home</Link></div> */}
      {/* <div className="p-4"> <Link href="/aboutme">About Me</Link></div> */}
      {/* <div className="p-4"> */}
      {/*   <a href="https://v />github.com/muh5329"> */}
      {/*     <Image */}
      {/*       src="/icons/github-mark.png" */}
      {/*       width={35} */}
      {/*       height={35} */}
      {/*       alt="github Logo" */}
      {/*     /> */}
      {/*   </a> */}
      {/* </div> */}
      {/**/}
      {/* <div className=""> */}
      {/*   <a href="https://www.linkedin.com/in/muneeb-haq-87b96098"> */}
      {/*     <Image */}
      {/*       src="/icons/In-Blue.png" */}
      {/*       width={35} */}
      {/*       height={35} */}
      {/*       alt="LinkedIn Logo" */}
      {/*     /> */}
      {/*   </a> */}
      {/* </div> */}
      --under construction--
      <ComboboxDropdownMenu />
    </nav >
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex flex-col gap-4 bg-red-400`}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
