
import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { ComboboxDropdownMenu } from "~/components/ui/menu";
import { useEffect } from "react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Monkey Factory",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="z-10 absolute top-0 right-0">
      <ComboboxDropdownMenu />
    </nav >
  );
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} flex flex-col gap-4 `}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
